### PR TITLE
Add François-René Rideau (formerly tunes@google.com) to credits section

### PR DESCRIPTION
**Pull request by tetromino**
As noted by brandjon@, he implemented Starlark mutability/freezing in 2015.

### CODE REVIEW

**Comment by brandjon** [comment]
@laurentlb FYI in case there's anything you want to add credits-wise.

**Comment by tetromino** [comment]
I've added further changes recommended by @laurentlb (and transitively by Damien).

**Review by laurentlb — APPROVED** [review]
The list looks good to me.

**Comment by adonovan** [comment]
Seems fine to me.

**Review by adonovan — APPROVED** [review]

**Pull request merged**
