### PR TITLE
go.mod: init Go module

### PR DESCRIPTION
**Pull request by zchee**
Initialize Go module support.

Close: #232

### CODE REVIEW

**Comment by zchee** [comment]
cc @alandonovan

**Comment by zchee** [comment]
@alandonovan sorry, just ping.

**Comment by alandonovan** [comment]
@jayconrod Jay, can you review this, as you are likely the world expert on Go modules?

Thanks @zchee and for the immense delay.

**Comment by alandonovan** [comment]
Got it, thanks Jay.

**Comment by zchee** [comment]
@alandonovan @jayconrod
Thanks for merge :)

**Pull request merged**
